# Generated by Django 5.2.4 on 2025-08-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('feedback', models.CharField(max_length=500)),
            ],
        ),
    ]
